#Плагин разработал TheRega.
#Если Вы обнаружите какой-либо баг, незамедлительно сообщите нам.
#Vk: vk.com/therega, группа: vk.com/waterstudio_ru


setblock: cobblestone

resoures:
  drop: false
  straight: false
  
exp: false

block-break:
  enable: true
  message: "actionbar:&cВы не можете ломать блоки в шахте."
  
drops-exp: false

block-place:
  enable: true
  message: "actionbar:&cВы не можете ставить блоки в шахте."
  
checks:
  gamemode:
    enable: true
    modes:
      - creative
      - spectator
    setmode: survival
    message: "actionbar:&cВы не можете пользоваться авто-шахтой в этом режиме игры."
  fly:
    enable: true
    message: "actionbar:&cВы не можете пользоваться авто-шахтой в режиме полёта."
    
messages:
  prefix: "&6Шахта &7> &f"
  
  commandmanager:
    no_commands: Для вас нет доступных команд.
    title_help: "Список команд:"
    command_not_found: Неизвестная команда.
    error: "&cЭта команда вызвала ошибку."
    no_permission: "&cНедостаточно прав."
    
  create:
    usage: "&e/regamine create <название> &f- Создать авто-шахту"
    no_selection: Пожалуйста выделите территорию для создание авто-шахты
    already: "&cДанная авто-шахта уже существует, придумайте другое название."
    complete: "Авто-шахта сохранена.;title:  &6&lШахта %nl% Авто-шахта сохранена."
    
  remove:
    usage: "&e/regamine remove <название> &f- Удалить авто-шахту"
    not-found: "&cДанной авто-шахты не существует."
    complete: "&aАвто-шахта успешно удалена."
    
  reset:
    usage: "&e/regamine resetall &f- Перезагрузить все блоки в авто-шахте"
    complete: "&aБлоки перезагружены."
    
  setsalary:
    usage: "&e/regamine setsalary <игрок> <зарплата> &f- Установить зарплату игроку"
    player-notfound: "Игрок не найден."
    double-exception: "Неверное число."
    complete: "Игроку &c%player% &fустановлена зарплата: &c%salary%$"
    
  addsalary:
    usage: "&c/regamine addsalary <игрок> <зарплата> &f- Добавить зарплату игроку"
    player-notfound: "Игрок не найден."
    double-exception: "Неверное число."
    complete: "Игроку &c%player% &fдобавлена зарплата, его зарплата составляет: &c%salary%$"
    
  takesalary:
    usage: "&c/regamine takesalary <игрок> <зарплата> &f- Убавить зарплату игроку"
    player-notfound: "Игрок не найден."
    double-exception: "Неверное число."
    complete: "Игроку &c%player% &fубавлена зарплата, его зарплата составляет: &c%salary%$"
    
  salary:
    usage: "&e/regamine salary &f- Получить зарплату"
    complete: "title:&aУспешно%nl%Вы получили зарплату в размере &e%salary%$"
    low: "title:&cОшибка%nl%Для получения зарплаты нужно добыть руду."
    
  block:
    complete: "actionbar:&l&f+ &e%earn%$"
    full: "actionbar:&cПридурок ты забил рюкзак"
    
ores:
  coal_ore:
    money: 1
    update: 5
    
  iron_ore:
    money: 2
    update: 10
    
  gold_ore:
    money: 3
    update: 15
    
  lapis_ore:
    money: 3
    update: 15
    
  redstone_ore:
    money: 4
    update: 20
    
  emerald_ore:
    money: 5
    update: 30
    
  diamond_ore:
    money: 5
    update: 30

# обновление ёпта

groups:
  default:
    max: 20
    booster: 1.0
  silver:
    max: 25
    booster: 1.5
  elder:
    max: 30
    booster: 2.0
  junior:
    max: 35
    booster: 2.0
  legend:
    max: 40
    booster: 2.0
  overlord:
    max: 45
    booster: 2.5
  neon:
    max: 50
    booster: 2.5
  furry:
    max: 55
    booster: 2.5
  dejavu:
    max: 60
    booster: 2.5
    
scoreboard:
  title: "&6&lШАХТА"
  values:
  - "&6&m┏  &7"
  - "&6| &8Уголь&7: &f%coal_ore%"
  - "&6| &fЖелезо&7: &f%iron_ore%"
  - "&6| &eЗолото&7: &f%gold_ore%"
  - "&6| &3Алмазы&7: &f%diamond_ore%"
  - "&6| &aИзумруды&7: &f%emerald_ore%"
  - "&6| &bЛазурит&7: &f%lapis_ore%"
  - "&6| &cРедстоун&7: &f%redstone_ore%"
  - "&6&m├  &5"
  - "&6| &7Рюкзак: %backpackCurrent% / %backpackMax%"
  - "&6| &dЗарплата: &a%salary%&7 &8(x%booster%&8)"
  - "&6&m├  &d"
  - "&6| &7Не забудь сдать руду!"
  - "&6&m┗  &1"
