name: RegaMine
main: fun.rega.RegaMine.Main
version: 1.0.0
author: TheRega
website: (vk.com/therega)
depend: [WorldEdit, WorldGuard, TitleManager, LuckPerms, Vault]


commands:
    rmine:
        description: Main executions sub commands.
        aliases: [rm, mine,regamine]
